import type { Metadata } from 'next';
import './globals.css';
import Navbar from '../components/Navbar';
import { BACKGROUND_CONFIG } from '@/constants';

export default function RootLayout(
  { children } : { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={BACKGROUND_CONFIG}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}